import { defineStore } from "pinia";

export const useChannelsStore = defineStore("channels", () => {
  const channels = ref([
    {
      id: 1,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: 3,
      tags: [
        {
          label: "spot",
          id: 1,
        },
      ],
      price: 23.2,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: true,
      background: "#B9B9B9",
    },
    {
      id: 2,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: 35,
      tags: [],
      price: 0,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: false,
      background: "#BB4040",
    },
    {
      id: 3,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: -4,
      tags: [
        {
          label: "spot",
          id: 1,
        },
      ],
      price: 0,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: false,
      background: "#AF28A2",
    },
    {
      id: 4,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: 3,
      tags: [
        {
          label: "spot",
          id: 1,
        },
      ],
      price: 23.2,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: true,
      background: "#B9B9B9",
    },
    {
      id: 5,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: 35,
      tags: [],
      price: 0,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: false,
      background: "#BB4040",
    },
    {
      id: 6,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: -4,
      tags: [
        {
          label: "spot",
          id: 1,
        },
      ],
      price: 0,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: false,
      background: "#AF28A2",
    },
    {
      id: 7,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: 3,
      tags: [
        {
          label: "spot",
          id: 1,
        },
      ],
      price: 23.2,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: true,
      background: "#B9B9B9",
    },
    {
      id: 8,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: 35,
      tags: [],
      price: 0,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: false,
      background: "#BB4040",
    },
    {
      id: 9,
      title: "Name Of Channel",
      caption: "Name of outer",
      lastProfit: -4,
      tags: [
        {
          label: "spot",
          id: 1,
        },
      ],
      price: 0,
      marketBase: "PAN - BTC",
      numOFSUB: 134,
      risk: "Medium",
      isSubscribed: false,
      background: "#AF28A2",
    },
  ]);
  return { channels };
});
