import { defineStore } from "pinia";

export const useCoinsStore = defineStore("coins", () => {
  const coins = [
    {
      index: {
        relatedHeaderId: 1,
        type: "favorite",
        align: "end",
        text: "",
        isFavorite: false,
      },
      Name: {
        relatedHeaderId: 2,
        type: "simple",
        align: "end",
        value: "Bitcoin(BTC)",
        icon: "bitcoin",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Price: {
        relatedHeaderId: 3,
        type: "simple",
        align: "end",
        value: "$12,935.5",
        icon: "",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Health: {
        relatedHeaderId: 4,
        type: "simple",
        align: "end",
        value: "Attractive",
        icon: "",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Sentiment: {
        relatedHeaderId: 5,
        type: "simple",
        align: "end",
        value: "Attractive",
        icon: "",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Volume: {
        relatedHeaderId: 6,
        type: "simple",
        align: "end",
        value: "$34,765,345,934",
        icon: "",
        caption: "2,687,684 BTC",
        valueColor: 0,
        captionColor: 1,
      },
      "24H": {
        relatedHeaderId: 7,
        type: "simple",
        align: "end",
        value: "+7%",
        icon: "",
        caption: "",
        valueColor: 2,
        captionColor: 1,
      },
      "7d": {
        relatedHeaderId: 8,
        type: "simple",
        align: "end",
        value: "-3%",
        icon: "",
        caption: "",
        valueColor: 3,
        captionColor: 1,
      },
      "Last 7 Days": {
        relatedHeaderId: 9,
        type: "line-chart",
        align: "end",
        value: [1, 20, 10, 13, 8],
      },
    },
    {
      index: {
        relatedHeaderId: 1,
        type: "favorite",
        align: "end",
        text: "",
        isFavorite: false,
      },
      Name: {
        relatedHeaderId: 2,
        type: "simple",
        align: "end",
        value: "Bitcoin(BTC)",
        icon: "bitcoin",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Price: {
        relatedHeaderId: 3,
        type: "simple",
        align: "end",
        value: "$12,935.5",
        icon: "",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Health: {
        relatedHeaderId: 4,
        type: "simple",
        align: "end",
        value: "Attractive",
        icon: "",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Sentiment: {
        relatedHeaderId: 5,
        type: "simple",
        align: "end",
        value: "Attractive",
        icon: "",
        caption: "",
        valueColor: 0,
        captionColor: 1,
      },
      Volume: {
        relatedHeaderId: 6,
        type: "simple",
        align: "end",
        value: "$34,765,345,934",
        icon: "",
        caption: "2,687,684 BTC",
        valueColor: 0,
        captionColor: 1,
      },
      "24H": {
        relatedHeaderId: 7,
        type: "simple",
        align: "end",
        value: "-23%",
        icon: "",
        caption: "",
        valueColor: 3,
        captionColor: 1,
      },
      "7d": {
        relatedHeaderId: 8,
        type: "simple",
        align: "end",
        value: "+11%",
        icon: "",
        caption: "",
        valueColor: 2,
        captionColor: 1,
      },
      "Last 7 Days": {
        relatedHeaderId: 9,
        type: "line-chart",
        align: "end",
        value: [8, 14, 5, 13, 1],
      },
    },
  ];
  const headers = [
    { label: "", sortable: false, align: "start", id: 1 },
    { label: "Name", sortable: false, align: "start", id: 1 },
    {
      label: "Price",
      sortable: true,
      sortType: 1,
      align: "end",
      id: 2,
    },
    { label: "Health", sortable: true, sortType: 1, align: "end", id: 3 },
    { label: "Sentiment", sortable: true, sortType: 1, align: "end", id: 4 },
    { label: "Volume", sortable: true, sortType: 1, align: "end", id: 5 },
    { label: "24h", sortable: true, sortType: 1, align: "end", id: 6 },
    { label: "7d", sortable: true, sortType: 1, align: "end", id: 7 },
    { label: "Last 7 Days", sortable: true, sortType: 1, align: "end", id: 8 },
  ];
  return { coins, headers };
});
